### PR TITLE
Add support for Swift 2

### PR DESCRIPTION
**Pull request by AndrewSB**
and Carthage

### CODE REVIEW

**Comment by fahlout** [comment]
Can you please make another pull request just for swift 2.0? I already merged Carthage support and now there is a conflict with your changes and the current code. Thanks!

**Comment by AndrewSB** [comment]
rebased :smile:

**Comment by fahlout** [comment]
Thanks! I'll update cocoa pods tomorrow.

**Comment by hiragram** [comment]
@fahlout When will you release swift 2.0 support on Cocoapods?

**Comment by dotmike** [comment]
+1

**Comment by phakaporns** [comment]
Dnjc

**Pull request merged**
